[tool.aerich]
tortoise_orm = "app.db.TORTOISE_ORM"
location = "./migrations"
src_folder = "./."

[tool.ruff]
show-fixes = true
line-length = 119
indent-width = 4

[tool.ruff.format]
quote-style = "single"

[tool.ruff.lint]
extend-select = ["E501"]
